# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskList', '0003_auto_20180522_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HIG', 'high'), ('MED', 'medium'), ('LOW', 'low')], default='LOW', max_length=3),
        ),
        migrations.AddField(
            model_name='task',
            name='repeats',
            field=models.CharField(choices=[('YEAR', 'every year'), ('MONT', 'every month'), ('WEEK', 'every week'), ('DAIL', 'every day')], default=None, max_length=4),
        ),
    ]
