# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskList', '0006_task_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='rank',
            field=models.DateField(blank=True, default=None),
        ),
    ]
