# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 19:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskList', '0009_auto_20180523_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField()),
                ('auther', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField()),
                ('auther', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurr_task_name', models.CharField(max_length=160)),
                ('recurr_last_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('recurring_pattern', models.CharField(blank=True, choices=[('YEAR', 'every year'), ('MONT', 'every month'), ('WEEK', 'every week'), ('DAIL', 'every day')], max_length=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_id_note', to='taskList.Task'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_id_feedback', to='taskList.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurr_task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taskList.RecurringTask'),
        ),
    ]
