# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 03:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskList', '0014_auto_20180523_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='event_due_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='start_date',
            new_name='event_start_date',
        ),
        migrations.AddField(
            model_name='task',
            name='event_end_time',
            field=models.TimeField(blank=True, default=datetime.time(23, 59, 59, 999999)),
        ),
        migrations.AddField(
            model_name='task',
            name='event_start_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
