# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskList', '0015_auto_20180524_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='group',
            name='member',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('RD', 'Research and Development'), ('MR', 'Marketing'), ('HR', 'Human Resource'), ('AF', 'Accounting and Finance')], default='IT', max_length=2),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
